### ISSUE TITLE
How to set null to the database?

### ISSUE THREAD

**Issue by kevindb** [arrilot/laravel-data-anonymization#4]
Using data-anonymization 1.1.0 on Laravel 5.6.39 on PHP 7.3.1
Thank you for your utility, it's super useful for cleaning up Prod data.

How would I replace the data in the DB field with _null_ instead of a string or other value?
Both of these attempts set an _empty string_ to the DB field instead of _null_.
```php
$table->column('image_url')->replaceWith(null);
```
and
```php
$table->column('image_url')->replaceWith(function() {
    return null;
});
```

**Comment by arrilot** [comment]
I've just released `arrilot/data-anonymization` 1.1.1 that should fix this issue.
Please test if it's true because I can't do it myself atm

**Comment by kevindb** [comment]
I gave 1.1.1 a try. It's closer, but still not working right. I get the error 
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE                                                                                                              
                      id='1'' at line 5 
```
I dumped the SQL and this is what it looks like
```sql
UPDATE\n
                    users\n
                SET\n
                    image_url = \n
                WHERE\n
                    id='1'
```
I think PHP evaluates `null` as an empty string. I tried changing the line to this, and it worked!
```php
$quotedValue = $value === null ? 'null' : $this->pdo->quote($value);
```
I opened [PR 6](https://github.com/arrilot/data-anonymization/pull/6) with the change. I hope this helps.

**Comment by arrilot** [comment]
Yeah, my bad, thanks.

1.1.2 is releazed
